### PR TITLE
Fix calculations about Transform(rotation)/Quaternion

### PR DESCRIPTION
**Pull request by MarshallW906**
- Fix incorrect implications and calculations in Transform::RotateAroundAxis. It now only rotates the object itself, locally, around specified axes
- `rtm::quat_from_euler_angles`'s rotation order is not what we want. Based on our test results in `test-input` and `test-input-2`, we shift the parameters passed into it (instead of directly modifying `rtm`), and negate two axes (`yaw` and `pitch`) to get expected results.

### CODE REVIEW

**Review by shurunxuan — COMMENTED** [review]
After testing, I feel like pitch and yaw should be negated, but not roll.

Don't know why.

**Comment by MarshallW906** [comment]
According to my test I feel like all the three axes should be negated

I'm thinking it might be just camera-behavior problem. Like someone prefers one way and others prefer the inverted pattern.

Also, in DirectXMath's doc:
https://learn.microsoft.com/en-us/windows/win32/api/directxmath/nf-directxmath-xmmatrixrotationrollpitchyaw
It says that “This is a left-handed coordinate system. To use right-handed coordinates, negate all three angles.” 
So I think we should avoid introducing a right hand system (Well I still don't quite know how exactly it works. Needs some calculations by hand)

**Comment by shurunxuan** [comment]
> I'm thinking it might be just camera-behavior problem. Like someone prefers one way and others prefer the inverted pattern.

I don't think so. The direction of a rotation should be well-defined.

For example, when the camera's pitch is growing bigger, in our left-handed system it should look down instead of up.

When the yaw is growing bigger, it should look right instead of left.

When the roll is growing bigger, it should rotate counter-clockwise instead of clockwise.

The roll is behaving the same as this but not the pitch and yaw. Thus I think only two of the axes need to be negated.

When you negate an axis, you are changing a left-handed coordinate system to a right-handed one. Negating two axis makes it back, thus we are not "introducing a right-handed system". We just have a different definition of a left-handed system with RTM.

**Comment by MarshallW906** [comment]
> For example, when the camera's pitch is growing bigger, in our left-handed system it should look down instead of up.
> 
> When the yaw is growing bigger, it should look right instead of left.
> 
> When the roll is growing bigger, it should rotate counter-clockwise instead of clockwise.

You are right. I mixed two questions in one. 

> When you negate an axis, you are changing a left-handed coordinate system to a right-handed one. Negating two axis makes it back
Yes I see. 

Also, the `CameraController` we test is using exact the same ascending/descending patten mentioned above, which is the reason why we can determine if two or none of the axes should be negated.

Change submitted. Two axes are negated, which is `yaw` and `pitch`

**Comment by MarshallW906** [comment]
Also it seems like we CANNOT get the rotation order we want (I believe it's left-handed ZXY) by simply shifting parameters and negating axes.

This is because the only thing we can achieve without modifying `rtm`'s implementations is to "mock" a different way treating `rtm`'s matrix and quaternion's `output`s. If we don't change `rtm`'s implementations we are not changing the way it **construct**s matrices/quaternions

**Comment by shurunxuan** [comment]
> Also it seems like we CANNOT get the rotation order we want (I believe it's left-handed ZXY) by simply shifting parameters and negating axes.
> 
> This is because the only thing we can achieve without modifying `rtm`'s implementations is to "mock" a different way treating `rtm`'s matrix and quaternion's `output`s. If we don't change `rtm`'s implementations we are not changing the way it **construct**s matrices/quaternions

Yeah that is true. I think with the system definition from RTM we should be able to just shift the order but it's not the case. So I'd say that RTM is doing something funky.

Anyway, I'm happy enough to just be able to keep our promise of using a left-handed coordinate system at the end of the day.

**Review by shurunxuan — APPROVED** [review]

**Comment by MarshallW906** [comment]
(See `test-input` to view)
I believe `rtm::quat_from_euler_angles` is using `XYZ` order, because when the camera is using `Quaternion::CreateFromYawPitchRoll()`, the `yaw` and `pitch` are always rotated as expected, without being affected by `roll`.
This means `roll` (i.e. Z-axis) is the last rotation.

Also, according to the result, it's apparent that `yaw` are always rotated relative to the extrinsic axis (`Vector3::Up` in our case), and `pitch` are applied after `yaw`.

Hence `XYZ`. Glad we have this resolved #32 :)

**Pull request merged**
