### PR TITLE
Refactor Math Interface

### LINKED ISSUE #16: Warning Elimination: type attributes ignored after type is already defined
Caused by redundant export attribute in forward declarations.

Emitted by: GCC

### LINKED ISSUE #21: Math Validation: conversion between `Matrix3x4f` and `Matrix4x4f`
```
return matrix4x4f{ vector_set_w(mtx.x_axis, zero), vector_set_w(mtx.y_axis, zero), vector_set_w(mtx.z_axis, zero), vector_set_w(mtx.w_axis, one) };
```

`rtm::matrix3x4f` actually stores 4 SIMD vectors and assume the last "logical row" always being `(0, 0, 0, 1)`. However the conversion from `3x4f` to `4x4f` is not directly copy the first three rows.

Functions that rely on the conversion from `rtm::matrix3x4f` to `rtm::matrix4x4` may be incorrect and needs re-writing

### PR DESCRIPTION
**Pull request by MarshallW906**
This will resolve issue #21

### CODE REVIEW

**Comment by MarshallW906** [comment]
Well if the target platform does NOT support SIMD, the fall back declaration of the `rtm` types are still struct, so we still need to care about the copy constructors `InterfaceType(const FakeSIMDType&)` and `InterfaceType(FakeSIMDType&&)`

**Comment by MarshallW906** [comment]
Okay now we have:
- Interface type (i.e. `gore::Vector3`)'s constructors from corresponding `SIMDValueType`, implemented by perfect forwarding
  - This also resolves #21 
- A true left-handed coord system (the previous code was copied from `SimpleMath` which uses right-handed coord)
- Some common math functions implemented

**Comment by shurunxuan** [comment]
Is it OK to fix #16 at the same time?

There is also a new warning emitted by GCC: 

```
warning: ignoring attributes in template argument ‘is_same_v<std::decay_t<_Tp>, gore::Vector3::SIMDValueType>’ [-Wignored-attributes]
```

**Comment by MarshallW906** [comment]
Yes, If it's not urgent. Otherwise, we merge this first and I will create a new branch right away.

Currently I don't have a clear thought on how to fix these warnings, will do some research before landing any changes.

**Comment by shurunxuan** [comment]
Let's fix #16 first before merging, and open a new branch for the ignored attribute one.

**Comment by MarshallW906** [comment]
Ok

**Comment by MarshallW906** [comment]
Resolved

**Review by shurunxuan — APPROVED** [review]

**Pull request merged**
